# Generated by Django 6.0 on 2025-12-12 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_model', models.CharField(choices=[('chatgpt', 'ChatGPT'), ('gemini', 'Gemini'), ('perplexity', 'Perplexity'), ('copilot', 'Microsoft Copilot'), ('google_ai', 'Google AI Overview'), ('claude', 'Claude')], max_length=50)),
                ('query', models.TextField(help_text='The query/prompt used')),
                ('mentioned', models.BooleanField(default=False, help_text='Was the brand mentioned?')),
                ('citation_context', models.TextField(blank=True, help_text='Context around the mention')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='brands.brand')),
            ],
            options={
                'verbose_name': 'AI Citation',
                'verbose_name_plural': 'AI Citations',
                'ordering': ['-date'],
            },
        ),
    ]
