# Generated by Django 6.0 on 2025-12-12 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=300)),
                ('position', models.IntegerField(help_text='Search result position (1-100)')),
                ('search_url', models.URLField(blank=True, max_length=1000)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='brands.brand')),
            ],
            options={
                'ordering': ['-date', 'position'],
                'unique_together': {('brand', 'keyword', 'date')},
            },
        ),
    ]
