# Generated by Django 6.0 on 2025-12-12 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('google', 'Google Reviews'), ('yelp', 'Yelp'), ('trustpilot', 'Trustpilot'), ('g2', 'G2'), ('capterra', 'Capterra'), ('glassdoor', 'Glassdoor')], max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, help_text='Rating out of 5', max_digits=2)),
                ('review_count', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='brands.brand')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('brand', 'platform', 'date')},
            },
        ),
    ]
