# Generated by Django 6.0 on 2025-12-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('software', 'Software & Technology'), ('ecommerce', 'E-Commerce & Retail'), ('finance', 'Finance & Accounting'), ('health', 'Health & Wellness'), ('food', 'Food & Beverage'), ('services', 'Professional Services'), ('other', 'Other')], default='other', max_length=50)),
                ('website', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
